from .register_user_input_controller import RegisterUserInputController
from .register_detection_results_controller import RegisterDetectionResultsController
from .list_historic_controller import ListHistoricController